# Generated by Django 4.1.7 on 2023-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/Devsearch_Profile.jpg', null=True, upload_to='images/'),
        ),
    ]
