# Generated by Django 4.1.7 on 2023-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesample',
            name='label',
            field=models.CharField(default='Image', max_length=50),
        ),
    ]
