# Generated by Django 4.1.7 on 2023-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_imagesample_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesample',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
