# Generated by Django 4.1.7 on 2023-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_imagesample_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ManyToManyField(blank=True, default='default.jpg', related_name='parentprojects', to='label.imagesample'),
        ),
    ]
