# Generated by Django 4.1.7 on 2023-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesample',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
