# Generated by Django 4.1.7 on 2023-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_alter_imagesample_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesample',
            name='featured_image',
            field=models.ImageField(blank=True, default='project_images/default.jpg', null=True, upload_to='project_images/'),
        ),
    ]
