# Generated by Django 4.1.7 on 2023-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_alter_imagesample_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_display_picture',
            field=models.ImageField(blank=True, default='project_display_picture/default.jpg', null=True, upload_to='project_display_picture/'),
        ),
    ]
